### ISSUE TITLE
Create LogoutHandler

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#47]
We need to be able to define a logout handler so that a "logout" link can be offered. 

This should clear out any session information regarding the current user profile (in the case of our vertx and pac4j infrastructure, this entails removal of the user profile held in the session for the vert.x infrastructure such as UserSessionHandler) and the pac4j user profile, also held in the session.

**Comment by leleuj** [comment]
About the name, it should be `ApplicationLogoutHandler` because this logout handler only destroys the local application pac4j session.
We have an issue: https://github.com/pac4j/pac4j/issues/54 I wish we could do for version 1.9. This one is a more global logout which would destroy the user session at the server level and which would certainly be triggered by another `LogoutHandler` (which could call the `ApplicationLogoutHandler` depending on the authentication mechanism).

**Comment by millross** [comment]
That’s slightly tricky in vert.x as it would be a requirement on the coder (not our library) to follow up with an ApplicationLogoutHandler, I guess we could make the wider logout handler redirect to a url which triggered our local logout subsequently (unless the wider logout implies calling the same as the local logout, ie it’s a superset of local logout). We could offer a composite of the two for the cases where both are required.

I’ll keep in mind your naming requirement for this - I’m soon going to be starting work on it.

**Comment by millross** [comment]
Added ApplicationLogoutHandler only - the fully destructive one could be created as well later, but I'd be keen to rename it something like a ClearSessionHandler so that it's clear to anyone using it that it's doing much more than a normal logout.
